// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    BackToSite: typeof import('./src/components/BackToSite.vue')['default']
    DownArrowIcon: typeof import('./src/components/icons/DownArrowIcon.vue')['default']
    Education: typeof import('./src/components/Education.vue')['default']
    EducationSection: typeof import('./src/components/EducationSection.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GithubIcon: typeof import('./src/components/icons/GithubIcon.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InstagramIcon: typeof import('./src/components/icons/InstagramIcon.vue')['default']
    InterestSection: typeof import('./src/components/InterestSection.vue')['default']
    LanguageSection: typeof import('./src/components/LanguageSection.vue')['default']
    LeftArrowIcon: typeof import('./src/components/icons/LeftArrowIcon.vue')['default']
    LinkedInIcon: typeof import('./src/components/icons/LinkedInIcon.vue')['default']
    MailIcon: typeof import('./src/components/icons/MailIcon.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MoonIcon: typeof import('./src/components/icons/MoonIcon.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    ProjectSection: typeof import('./src/components/ProjectSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionPart: typeof import('./src/components/SectionPart.vue')['default']
    SectionTitle: typeof import('./src/components/SectionTitle.vue')['default']
    SocialList: typeof import('./src/components/SocialList.vue')['default']
    Stack: typeof import('./src/components/Stack.vue')['default']
    StackSection: typeof import('./src/components/StackSection.vue')['default']
    SunIcon: typeof import('./src/components/icons/SunIcon.vue')['default']
    TwitterIcon: typeof import('./src/components/icons/TwitterIcon.vue')['default']
    WorkExperience: typeof import('./src/components/WorkExperience.vue')['default']
    WorkSection: typeof import('./src/components/WorkSection.vue')['default']
  }
}
